version: '3.7'

services:
    players:
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        volumes:
            - .:/usr/src/app
        ports:
            - 5001:5000
        environment:
            - FLASK_APP=project/__init__.py
            - FLASK_ENV=development
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@players-db:5432/players_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@players-db:5432/players_test
        depends_on:
            - players-db

    players-db:
        build:
            context: ./project/db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres